function [fminopt, psopt] = make_optim_options()
    % Simply returns options for the optimizers used in the study

    % FMINCON OPTIONS
    fminopt = optimset('TolFun'      , 1e-14, ...
                       'TolX'        , 1e-14, ...
                       'Display'     , 'off', ...
                       'MaxFunEvals' ,   [], ...
                       'MaxIter'     ,   []);

    % PATTERNSEARCH OPTIONS
    psopt = psoptimset( ...
        'PollMethod'            , 'gpspositivebasis2n',  ...
        'CompletePoll'          , 'on',                  ...
        'PollingOrder'          , 'consecutive',         ...
        'CompleteSearch'        , 'off',                 ...
        'SearchMethod'          , [],                    ...
        'MeshAccelerator'       , 'off',                 ...
        'ScaleMesh'             , 'on',                  ...
        'MeshExpansion'         , 2,                     ...
        'MeshContraction'       , 0.5,                   ...
        'TolMesh'               , 1e-14,                 ...
        'TolX'                  , 1e-14,                 ...
        'TolFun'                , 1e-14,                 ...
        'MaxIter'               , [],                   ...
        'MaxFunEvals'           , [],                   ...
        'Display'               , 'off'                  ...
        );
end
